name: "brats_mri_segmentation"
platform: "pytorch_libtorch"
max_batch_size: 1

input [
  {
    name: "INPUT__0"
    data_type: TYPE_FP32
    dims: [ 4, 240, 240, 160 ]
  }
]

output [
  {
    name: "OUTPUT__0"
    data_type: TYPE_FP32
    dims: [ 3, 240, 240, 160 ]
  }
]

instance_group [
  {
    count: 1
    kind: KIND_CPU
  }
]
