"""
SegResNet Training Script for Brain Tumor Segmentation.

Trains a MONAI SegResNet on the locally generated synthetic BraTS-format cases.
Saves weights to: triton/model_repository/brain_tumor_segresnet/weights.pth

Usage:
    python scripts/train_segmentation.py [--epochs 30] [--lr 1e-3] [--device cpu]

Training data: data/samples/ (generated by data_generator/generate_synthetic_cases.py)
"""

import argparse
import sys
import os
import glob
from pathlib import Path

import numpy as np
import nibabel as nib

# ── Optional: torch + MONAI ───────────────────────────────────────────────
try:
    import torch
    import torch.nn as nn
    import torch.optim as optim
    from torch.utils.data import Dataset, DataLoader
    TORCH_OK = True
except ImportError:
    print("[ERROR] PyTorch not installed. Run: pip install torch")
    sys.exit(1)

try:
    from monai.networks.nets import SegResNet
    from monai.losses import DiceLoss
    from monai.transforms import (
        Compose, NormalizeIntensityd, EnsureTyped, RandFlipd,
        RandRotate90d, RandScaleIntensityd, RandShiftIntensityd,
    )
    MONAI_OK = True
except ImportError:
    print("[ERROR] MONAI not installed. Run: pip install monai")
    sys.exit(1)

# ── Paths ─────────────────────────────────────────────────────────────────
PROJECT_ROOT = Path(__file__).resolve().parent.parent
SAMPLES_DIR  = PROJECT_ROOT / "data" / "samples"
WEIGHTS_DIR  = PROJECT_ROOT / "triton" / "model_repository" / "brain_tumor_segresnet"
WEIGHTS_PATH = WEIGHTS_DIR / "weights.pth"


# ---------------------------------------------------------------------------
# Dataset
# ---------------------------------------------------------------------------

class BraTSCaseDataset(Dataset):
    """
    Loads all generated NIfTI cases from data/samples/.
    Returns:
        image: [4, D, H, W] float32  (T1, T1ce, T2, FLAIR)
        label: [D, H, W]   uint8     (0/1/2/3 — BraTS labels)
    """

    def __init__(self, samples_dir: Path, augment: bool = True):
        self.cases   = []
        self.augment = augment

        # Find all case directories
        for case_dir in sorted(samples_dir.iterdir()):
            if not case_dir.is_dir():
                continue
            for timepoint in ["scan_A_baseline", "scan_B_followup"]:
                tp_dir = case_dir / timepoint
                prefix = "baseline" if "baseline" in timepoint else "followup"
                seg_file = tp_dir / f"{prefix}_seg.nii.gz"
                if not seg_file.exists():
                    continue
                modals = {
                    seq: tp_dir / f"{prefix}_{seq}.nii.gz"
                    for seq in ["t1", "t1ce", "t2", "flair"]
                }
                if all(p.exists() for p in modals.values()):
                    self.cases.append({"modals": modals, "seg": seg_file})

        print(f"[Dataset] Found {len(self.cases)} valid training volumes.")

        # MONAI augmentation pipeline
        self.aug_transform = Compose([
            RandFlipd(keys=["img", "seg"], prob=0.5, spatial_axis=0),
            RandFlipd(keys=["img", "seg"], prob=0.5, spatial_axis=1),
            RandRotate90d(keys=["img", "seg"], prob=0.4, max_k=3, spatial_axes=(0, 1)),
            RandScaleIntensityd(keys=["img"], factors=0.1, prob=0.5),
            RandShiftIntensityd(keys=["img"], offsets=0.1, prob=0.5),
        ])

    def __len__(self):
        return len(self.cases)

    def _load_nifti(self, path: Path) -> np.ndarray:
        img = nib.load(str(path))
        return img.get_fdata(dtype=np.float32)

    def _normalize(self, arr: np.ndarray) -> np.ndarray:
        """Nonzero z-score normalization."""
        mask = arr > 0
        if mask.any():
            mu, sigma = arr[mask].mean(), arr[mask].std()
            out = np.zeros_like(arr)
            out[mask] = (arr[mask] - mu) / (sigma + 1e-7)
            return out
        return arr

    def __getitem__(self, idx: int):
        case = self.cases[idx]

        channels = []
        for seq in ["t1", "t1ce", "t2", "flair"]:
            vol = self._load_nifti(case["modals"][seq])
            vol = self._normalize(vol)
            channels.append(vol)

        image = np.stack(channels, axis=0)          # [4, D, H, W]
        seg   = self._load_nifti(case["seg"]).astype(np.int64)  # [D, H, W]

        if self.augment:
            data = {"img": image, "seg": seg}
            data = self.aug_transform(data)
            image, seg = data["img"], data["seg"]

        return (
            torch.from_numpy(np.ascontiguousarray(image)).float(),
            torch.from_numpy(np.ascontiguousarray(seg)).long(),
        )


# ---------------------------------------------------------------------------
# Dice metric helper
# ---------------------------------------------------------------------------

def dice_score(pred: torch.Tensor, target: torch.Tensor, num_classes: int = 4) -> float:
    """Mean Dice score across foreground classes (1, 2, 3)."""
    pred_soft = torch.softmax(pred, dim=1)
    pred_hard = pred_soft.argmax(dim=1)

    scores = []
    for c in range(1, num_classes):   # skip background
        p = (pred_hard == c).float()
        t = (target == c).float()
        intersection = (p * t).sum()
        denom = p.sum() + t.sum()
        if denom > 0:
            scores.append((2.0 * intersection / denom).item())

    return float(np.mean(scores)) if scores else 0.0


# ---------------------------------------------------------------------------
# Training loop
# ---------------------------------------------------------------------------

def train(epochs: int = 30, lr: float = 1e-3, device_str: str = "cpu", batch_size: int = 1):
    # ── Device ───────────────────────────────────────────────────────────
    if device_str == "auto":
        if torch.cuda.is_available():
            device = torch.device("cuda")
        elif hasattr(torch.backends, "mps") and torch.backends.mps.is_available():
            device = torch.device("mps")
        else:
            device = torch.device("cpu")
    else:
        device = torch.device(device_str)
    print(f"[Train] Device: {device}")

    # ── Dataset & Loader ─────────────────────────────────────────────────
    if not SAMPLES_DIR.exists() or not any(SAMPLES_DIR.iterdir()):
        print("[Train] No cases found. Generating synthetic data first…")
        sys.path.insert(0, str(PROJECT_ROOT))
        from data_generator.generate_synthetic_cases import generate_all_cases
        generate_all_cases(str(SAMPLES_DIR))

    dataset = BraTSCaseDataset(SAMPLES_DIR, augment=True)
    if len(dataset) == 0:
        print("[ERROR] No valid training volumes found. "
              "Ensure segmentation masks (e.g. baseline_seg.nii.gz) exist in data/samples/.")
        sys.exit(1)

    loader = DataLoader(dataset, batch_size=batch_size, shuffle=True,
                        num_workers=0, pin_memory=False)

    # ── Model ─────────────────────────────────────────────────────────────
    model = SegResNet(
        blocks_down=(1, 2, 2, 4),
        blocks_up=(1, 1, 1),
        init_filters=16,
        in_channels=4,
        out_channels=4,
        dropout_prob=0.1,
    ).to(device)

    optimizer  = optim.AdamW(model.parameters(), lr=lr, weight_decay=1e-5)
    scheduler  = optim.lr_scheduler.CosineAnnealingLR(optimizer, T_max=epochs, eta_min=1e-5)
    dice_loss  = DiceLoss(to_onehot_y=True, softmax=True, reduction="mean")
    ce_loss    = nn.CrossEntropyLoss()

    # ── Output dir ────────────────────────────────────────────────────────
    WEIGHTS_DIR.mkdir(parents=True, exist_ok=True)

    print(f"\n[Train] Starting training: {epochs} epochs, LR={lr}")
    print("-" * 60)

    best_dice = 0.0
    for epoch in range(1, epochs + 1):
        model.train()
        epoch_loss  = 0.0
        epoch_dice  = 0.0
        n_batches   = 0

        for images, labels in loader:
            images = images.to(device)             # [B, 4, D, H, W]
            labels = labels.to(device)             # [B, D, H, W]

            optimizer.zero_grad()
            logits = model(images)                 # [B, 4, D, H, W]

            # Combined Dice + CrossEntropy loss (standard BraTS training objective)
            loss_d = dice_loss(logits, labels.unsqueeze(1))
            loss_c = ce_loss(logits, labels)
            loss   = 0.6 * loss_d + 0.4 * loss_c

            loss.backward()
            nn.utils.clip_grad_norm_(model.parameters(), max_norm=1.0)
            optimizer.step()

            batch_dice   = dice_score(logits.detach(), labels.detach())
            epoch_loss  += loss.item()
            epoch_dice  += batch_dice
            n_batches   += 1

        scheduler.step()

        avg_loss = epoch_loss / max(n_batches, 1)
        avg_dice = epoch_dice / max(n_batches, 1)

        print(f"Epoch {epoch:3d}/{epochs}  |  Loss: {avg_loss:.4f}  |  Dice: {avg_dice:.4f}")

        # Save best checkpoint
        if avg_dice >= best_dice:
            best_dice = avg_dice
            torch.save(model.state_dict(), str(WEIGHTS_PATH))
            print(f"            ✓ New best Dice: {best_dice:.4f} — weights saved.")

    print(f"\n[Train] Training complete. Best Dice: {best_dice:.4f}")
    print(f"[Train] Weights saved to: {WEIGHTS_PATH}")
    return best_dice


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Train BraTS SegResNet on synthetic cases.")
    parser.add_argument("--epochs",  type=int,   default=30,   help="Number of training epochs")
    parser.add_argument("--lr",      type=float, default=1e-3, help="Initial learning rate")
    parser.add_argument("--device",  type=str,   default="auto", help="cpu | cuda | mps | auto")
    parser.add_argument("--batch",   type=int,   default=1,    help="Batch size")
    parser.add_argument("--gen-data",action="store_true",      help="Re-generate synthetic cases before training")
    args = parser.parse_args()

    if args.gen_data:
        sys.path.insert(0, str(PROJECT_ROOT))
        from data_generator.generate_synthetic_cases import generate_all_cases
        generate_all_cases(str(SAMPLES_DIR))

    train(epochs=args.epochs, lr=args.lr, device_str=args.device, batch_size=args.batch)
